name: Describe failure
description: Describe CI/CD failure with GPT-4

inputs:
  openai-token:
    description: 'OpenAI Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run assistant
      run: cd lib/cicd-assistant && npm ci > '/dev/null' 2>&1 && npm run build > '/dev/null' 2>&1 && npm run start
      shell: bash
      env:
        OPENAI_TOKEN: ${{ inputs.openai-token }}
