name: PR Code Review

on:
  pull_request:
    branches:
      - master

jobs:
  code-review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REPO_NAME: ${{ github.repository.name }}
      REPO_OWNER: ${{ github.repository_owner }}
      ISSUE_NUMBER: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Prepare lib
        run: cd lib/code-reviewer && npm ci && npm run build && npm run review

      # - name: Print git diff content without pagination
      #   run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
