name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit

  deploy-vercel:
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
