name: Healthcheck

on:
  workflow_dispatch:
  schedule:
    # min hour day month day-of-week
    - cron: '* * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Run healthcheck
        uses: ./.github/actions/notify-slack
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Healthcheck completed successfully!'
          type: 'good'

      - name: Run healthcheck
        uses: ./.github/actions/notify-slack
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Healthcheck failed!'
          type: 'danger'
